version: '3.4'

services:

  weaviate:
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: semitechnologies/weaviate:latest
    ports:
    - 8080:8080
    environment:
      IMAGE_INFERENCE_API: http://i2v-neural:8080
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural,text2vec-contextionary'
      CLUSTER_HOSTNAME: 'node1'

  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    init: true
    environment:
      ENABLE_CUDA: '0'

  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
    ports:
    - 9999:9999
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
...
